### ISSUE TITLE
Bug: doesn't work when task is removed

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [fennifith/Alarmio#100]
## Device Info

- Brand: `Pixel 4 but also emulator`
- Model name: `Google`
- Android version: `Stock - 30 or 29`

## Steps to Reproduce
set alarm to be 1 minute from now.
remove from recent tasks.
Wait a minute.

Alarm doesn't get triggered.

[2020-02-27_13-52-57.zip](https://github.com/fennifith/Alarmio/files/4261456/2020-02-27_13-52-57.zip)

Other apps (such as[ "Clock" by Google](https://play.google.com/store/apps/details?id=com.amdroidalarmclock.amdroid) and [this one](https://play.google.com/store/apps/details?id=com.amdroidalarmclock.amdroid)) manage to handle it just fine, somehow.

**Comment by raboof** [comment]
I think I can reproduce this. When I look a the logs with `adb logcat` when testing this, I see:

```
W ActivityTaskManager: Background activity start [callingPackage: me.jfenn.alarmio; callingUid: 10261; isCallingUidForeground: false; isCallingUidPersistentSystemProcess: false; realCallingUid: 10261; isRealCallingUidForeground: false; isRealCallingUidPersistentSystemProcess: false; originatingPendingIntent: null; isBgStartWhitelisted: false; intent: Intent { flg=0x10000000 cmp=me.jfenn.alarmio/.activities.AlarmActivity (has extras) }; callerApp: ProcessRecord{49d5ba9 5229:me.jfenn.alarmio/u0a261}]
```

So I guess this means we're not allowed to get started when in the background (perhaps https://developer.android.com/about/versions/oreo/background is relevant here?).

Would be interesting to figure out what's the difference with those other apps, indeed.

**Comment by AndroidDeveloperLB** [comment]
Any idea how could it be?

**Comment by raboof** [comment]
So, interestingly, this morning my alarm worked fine, while I'm pretty sure Alarmio was not in the foreground.

Checking the logcat output now, however, doesn't reveal *any* trace of this, even though I added some diagnostig `Log.i` calls in places like `AlarmActivity`'s constructor and `onCreate`.

I'm pretty new to Android development, so there's probably something going on here that I don't understand yet. Would love to learn! :)

**Comment by AndroidDeveloperLB** [comment]
Maybe do as done here in the last edit :
https://stackoverflow.com/a/60323379/878126
https://github.com/AndroidDeveloperLB/AlarmClockSample
https://github.com/yuriykulikov/AlarmClock

**Comment by fennifith** [comment]
I'm going to merge this into #85 as it covers the same issue.

As @AndroidDeveloperLB says, it seems that `SYSTEM_ALERT_WINDOW` is a solution - though a bit of a strange one, in my opinion - the [android docs](https://developer.android.com/guide/components/activities/background-starts) mention that this permission grants an exemption from background restrictions. These requirements should already be satisfied by the `PendingIntent` from the AlarmManager, though... I guess some devices might ignore that detail.

**Comment by AndroidDeveloperLB** [comment]
@fennifith According to [what I wrote on StackOverflow](https://stackoverflow.com/a/60323379/878126), even though the code here needs to be updated, the issue I've found on my POC was of Android Studio itself. For some reason it happened only if starting from there.

**Comment by fennifith** [comment]
@AndroidDeveloperLB ah, I only skimmed that comment; @ajayyy was able to reproduce the issue, and granting `SYSTEM_ALERT_WINDOW` did indeed provide a solution. I agree that this is a different issue from the one mentioned on stackoverflow, but going by current testing (and the Android documentation itself) it seems like this will solve the problem that is occurring.

As far as I can tell, the issue here is not that AlarmManager fails to start the app - it seems like the BroadcastReceiver is starting properly at the time of the alarm, but failing to open the actual activity that should notify the user.

**Comment by ajayyy** [comment]
From what I've been reading, the goal is to prevent apps from starting activities from the background **while the screen is on**. The method to achieve similar effects on Android 10 without the extra permission is to use a notification with a full screen intent.

When the screen is off, this will create the activity. When the screen is on, this will only create a notification. Presumably, the goal was to prevent apps from starting ad activities in the background (this happened).

However, enabling that permission is a much simpler fix that is better anyway since you don't just have a notification while the screen is on.

**Comment by AndroidDeveloperLB** [comment]
@ajayyy Right. This is what I also know.
People who develop alarm clock apps should provide the user an option, to always show the Activity (uses SAW permission, for example), or use the standard way that won't appear when the screen is turned on.

**Comment by fennifith** [comment]
@AndroidDeveloperLB Alarmio does not have that functionality, and I'm not interested in putting in the time to develop it right now. I won't turn down any pull requests or contributions to make the SAW permission optional in the future - and I might even implement it myself if there is enough actual demand for it - but currently, this behavior is breaking the app, and adding the permission is the simplest way to correct it.

I'm going to assume that _the majority_ of Alarmio's users will probably want their alarms to actually show up on the screen when they are triggered, not just create some notification in the background that could potentially be missed (even with a sound/vibration, it might not be obvious where it was coming from unless the actual content of the screen were to change). Regardless, it's currently doing neither, and I think everyone would prefer to grant one extra permission for it to function reliably than have it not work on their device at all.

Proposal: continue with the SAW permission (as planned), and create a separate issue for implementing an option to use the "intended" behavior of background notifications in Android 10 and above. Good compromise?

**Comment by ajayyy** [comment]
Yes, please don't do extra work for no reason. I think the extra permission workaround is the best since it is not too hard to implement

**Comment by AndroidDeveloperLB** [comment]
@fennifith If you don't intend to add this feature, there is no need for this permission. Just use the standard way like Google's Clock app and that's it.

The notification appears ONLY if the screen is already turned on. This prevents showing up when the user is using the phone, like on a game or a playing video or browsing the Internet.

And it's way easier to use and implement than to have SAW, while having to show an Activity.

**Comment by ajayyy** [comment]
@AndroidDeveloperLB It is not easier to implement. The code currently launches an activity. Making it work with SAW just requires adding a line to the manifest and making the app send you to the settings page on setup.

Implementing using a notification would require a rework of the entire alarm system.

**Comment by AndroidDeveloperLB** [comment]
That's incorrect. You have to also add a check that if the permission is denied, you show a notification instead, which is exactly what you should do anyway.

It doesn't need any rework at all. It's a simple notification, which you are supposed to add anyway.

**Comment by ajayyy** [comment]
@AndroidDeveloperLB I was trying to implement it with notifications but ran into a lot of trouble with some sparse docs due to Android 10 being new.

If the permission is denied, it can just go back to the current behavior or only working if not closed from recent apps.

**Comment by AndroidDeveloperLB** [comment]
@ajayyy What lots of trouble?
Here, attached a POC showing how to do it.
[EasyWakeAlarmClock.zip](https://github.com/fennifith/Alarmio/files/4411457/EasyWakeAlarmClock.zip)

Based on StackOverflow question I asked here:
https://stackoverflow.com/q/57964961/878126

Important note:
DO NOT start from the IDE. Start only from launcher.

**Comment by fennifith** [comment]
@AndroidDeveloperLB Here's a suggestion - instead of telling me how easy it is to work on my app, why don't you try to implement this yourself and make a pull request instead of nagging us to do this work for you. Right now, I don't see why I or any other contributors should have any obligation to implement this when the current solution seems to work perfectly fine. Nobody does this as their full-time job, none of us are getting paid to work on it - it's not like we get any bonus points for going out of our way and "doing it correctly." This is a trivial distinction that only affects newer Android devices (I suspect, being an open source project with a minSdk of 16, that many of our users are actually on older phones that this wouldn't change a thing for) and I think our time could be much better spent elsewhere.

From what I can tell, your proposed modifications involve:
- creating a notification channel for the alarm
- invoking a background service that will either show that notification or start the proper activity
- changing the broadcast receiver to start that service instead of launching the `AlarmActivity` as it currently does
- adding a switch to the settings menu to allow users to choose between these behaviors

This would also need some fairly thorough testing to make sure there aren't any more side-effects to its use, and ensure there are no (additional) bugs introduced in this process.

On the other hand, adding the `SYSTEM_ALERT_WINDOW` permission (which I have already done, by the way) literally involved appending one single line to the manifest and creating a dialog/intro page for when the user first opens the app. It pretty much guarantees that the existing code will continue to work on newer Android versions, and won't introduce any bugs for other users as _none of the actual behavior will have changed_.

I would like to put some effort into making the app operate correctly in the case that users do not grant this permission - this is why I proposed creating an alternate issue to address this in the future. However, this is not something I am interested in doing right now; especially as there are many other arguably more important bugs that I would like to resolve first (take #40 or #98 as an example). To conclude: if you want this, implement it yourself. Otherwise... not getting done. Sorry.

**Comment by AndroidDeveloperLB** [comment]
I already told you why:
1. SAW is going to be fully deprecated according to Google. I believe it won't, but maybe it will become supervised instead.
2. SAW is going to be annoying to be granted on R (needs to find the app)
3. SAW is not the standard way to handle alarm clock apps.
4. Alarm clock apps shouldn't appear like a spammy ad, showing all of a sudden in the middle of doing something else. Even a phone call doesn't do it and uses the same mechanism of showing a notification, gently
5. It's always better to avoid a permission when the OS allows. Adding a permission can also drive people away when there are alternatives that don't need it.
6. It's actually easier and shorter to avoid SAW and use the standards.
7. The built in alarm clock app doesn't need SAW and it works fine. Same goes for another open sourced project that doesn't need SAW and works fine.

No way you added just a single line. You have to check if the permission is granted, including when the alarm is fired. If it's not granted, you should use the fallback: use the standard API. 
Otherwise nothing will appear. It's better to show something than nothing.

**Comment by ajayyy** [comment]
@AndroidDeveloperLB All your info is correct, and good to note. However, @fennifith clearly does not have the time to work on this **at the current time**. So, unless someone contributes, it probably won't happen. He said he'll create an issue to address adding it potentially at some other time, or for someone else to add it. If you'd like to implement it, you can try.

**Comment by AndroidDeveloperLB** [comment]
@ajayyy Why create a new issue ? Why close this one? Where is the new one?

It's still about the same topic: the app doesn't work as it should. Not having the time doesn't mean anything about the existance of the issue.

Suppose I had an Android Go device with this app. Now I won't be able to use it, because it will force me to grant a permission that can't be granted.
An alarm clock app can't be used on an Android Go device...

The SAW trick should not be used as a full solution. It should be an optional feature, for those who want to see it in full screen.
Even WhatsApp, which had a similar feature (shows a popup right away when you get a message) - doesn't have it anymore. They could use the same approach, or even a gentle one: request when the user enables it. 
Instead, they have a disabled setting "popup notification". They show a dialog (when you press on it anyway) saying "popup notifications are no longer available in your version of Android":

![image](https://user-images.githubusercontent.com/5357526/78080599-3d20f180-73b7-11ea-8e67-18589be55b0c.png)

**Comment by AndroidDeveloperLB** [comment]
@fennifith The sample I provided was after various playing around, BTW. It can be smaller, depending on what you want to achieve.

**Comment by raboof** [comment]
> I think I can reproduce this.

Hrm. I'm pretty sure I was at c31de6e1b60da8c02bfc66108a8408996437302c when I tested this, but I tried again today and I can't get it to fail anymore :(

**Comment by AndroidDeveloperLB** [comment]
The current way it was "fixed" is by adding SAW permission to let it start an Activity even when in the background. Read above to see its disadvantages.
One of the most terrible ones is the inability to use it on Android Go devices, because SAW can't even be granted there anymore.
An alarm clock app that can't be used on low end devices...

**Comment by raboof** [comment]
> inability to use it on Android Go devices, because SAW can't even be granted there anymore.

Yes, we understand this limitation, and we would like to see it fixed. I personally don't have such a device, so I'm personally not currently planning to fix it.

I'm not sure what to make of your participation in this thread. On the one hand you're clearly involved, going to great lengths to share your knowledge, which is helpful and much appreciated. On the other hand, and this might be due to a language barrier, you seem somehow angry/frustrated(?) about it, but I'm not sure if I'm reading that right, and if I'm reading it right, I'm not sure what you're angry/frustrated about. If it's the fact that we haven't fixed this issue yet despite your advice: you'll agree it's *some* work (otherwise it'd have been easy to just provide a PR), and we all have our own personal priorities.

**Comment by AndroidDeveloperLB** [comment]
I'm more frustrated about Google causing this issue. I'm very involved in writing issues to them, and this was one of them.
And recently I wrote a bug report that I spent too much time about it (including on StackOverflow, and including putting a bounty), of having an alarm not being triggered because it was removed from the recent tasks, even though I've done everything according to what is supposed to be done (the POC I've shared is something I did on the way). In the end, it was actually the IDE's fault (issue exists only if launched from IDE), and the bounty was for nothing (was granted initially automatically to some random person who didn't help at all).
Later I wrote here about this, and I still don't get why after trying to help and explain how it's supposed to work, I get downvoted.
I've spent a lot of time on this and I tried to help a random app that I've found. I reached here because I wanted to see how well some open sourced apps perform. This one was not working well so I reported about it. On another it was very complex but working well, but again only if not launched from the IDE.

So, I want to at least see that this app gets to do it right. :)
Take whatever you wish from the links I've provided.

**Comment by raboof** [comment]
> I'm more frustrated about Google causing this issue

Yeah, that's understandable! I'm not really a mobile developer, but it seems like a bit of a moving target - which sometimes is necessary, but I can imagine is also frustrating if it doesn't bring much actual advantage.

> I've spent a lot of time on this and I tried to help a random app that I've found

Yes, thanks for that!!

> I still don't get why after trying to help and explain how it's supposed to work, I get downvoted.

I suspect this was not because of content, but because of tone. FLOSS developers often get a lot of questions, but also criticism and "demands" from people - often from people who don't contribute to the project. That can be very frustrating when it happens regularly and you're already giving up your precious free time to get the project to where it is today. Starting the post with "I already told you why:", and including things like "!?", "you have to" and "you should" makes it read like you might be "such a person", even if it's probably not intended in that way, and you're sharing useful information here. Of course I can't speak for others, but I can certainly imagine that might have triggered some bad memories and lead to those thumbs-down.

**Comment by AndroidDeveloperLB** [comment]
I wrote it from experience with this topic, as I've tried to handle alarms for a different purpose (not of alarm clock, but still wanted to do the research to understand how it's done). 

As a user, I don't even use this app and not even the other open sourced app I've mentioned. I use the one of Google.

**Comment by raboof** [comment]
Yes, that is definitely appreciated!

**Comment by AndroidDeveloperLB** [comment]
Still, this was closed for some reason. How come?

**Comment by fennifith** [comment]
@AndroidDeveloperLB This issue was closed because it is a duplicate of #85, which _already existed in the issue tracker_ and describes the same problem.

#85 will be closed after the next release because it will be fixed (for the most part) with the addition of `SYSTEM_ALERT_WINDOW`.

I created #107 as a separate issue because it describes a different problem which will be fixed on its own timeline, and so that contributors don't have to read through the 30 pedantic comments this issue has accumulated to understand what the actual problem is and what needs to be done to solve it.

**Comment by AndroidDeveloperLB** [comment]
It's not pedantic. It's how an alarm clock is supposed to work, and any other thing that uses it.
You are seeing SAW as a real fix and it's wrong.
Using SAW is the exception. It's a workaround for a problem that doesn't really exist. Not a fix. It was never needed for an alarm clock. An alarm clock is not supposed to steal attention from the user while he's doing something.
The proper usage of the API for an alarm clock existed for a long time, using a foreground notification.
Please check Google's Clock app. You will see how it works, that it doesn't bother users in case the device screen is turned on.
This was supposed to be implemented from the beginning. It should have been top priority and not the opposite.
You are saying it all as if it's a new thing to create an alarm clock app, but setFullScreenIntent is from API 11. That's ages ago:
https://developer.android.com/reference/android/app/Notification.Builder#setFullScreenIntent(android.app.PendingIntent,%20boolean)

> An intent to launch instead of posting the notification to the status bar. Only for use with extremely high-priority notifications demanding the user's immediate attention, such as an incoming phone call or alarm clock that the user has explicitly set to a particular time. 

If you want to understand it, you should read about it.
Here, some more links:

https://developer.android.com/training/notify-user/time-sensitive

https://developer.android.com/guide/components/activities/background-starts

> In nearly all cases, apps that are in the background should display time-sensitive notifications to provide urgent information to the user instead of directly starting an activity. Examples of when to use such notifications include handling an incoming phone call or an active alarm clock.
> 
> This notification-based alert and reminder system provides several advantages for users:
> 
> When using the device, the user is shown a heads-up notification that allows them to respond. The user maintains their current context and has control over the content that they see on the screen.
> Time-sensitive notifications respect the user's Do Not Disturb rules. For example, users might permit calls only from specific contacts, or repeat callers, when Do Not Disturb is enabled.
> When the device's screen is off, your full-screen intent is launched immediately.
> In the device's Settings screen, the user can see which apps have recently sent notifications, including from specific notification channels. From this screen, the user can control their notification preferences.

I said it before. I say it again: SAW is not how alarm clock apps are supposed to be created.
You should use the standard API that has existed for a long time. Using SAW should be optional for people who wan the exceptional behavior, or appearing in full screen even if they are doing something.

**Comment by fennifith** [comment]
@AndroidDeveloperLB You've proved your point. Congratulations.

I would very much like this to be fixed in Alarmio. Would you like to be the one to fix it? Because, as I believe I've said numerous times, _I don't have the time to fix and test and maintain a drastic change to Alarmio's codebase all by myself._ If that means that Alarmio is an inferior and broken app, so be it. I have more important priorities for myself; studying for college exams being one of them.

As I said in the new issue, _this is a pretty low priority for me,_ because myself and the vast majority of users are not affected by this one way or another; it still acts the same on _most devices_ regardless. However, it seems that you don't see it that way. Obviously, we have different priorities. Nowhere have I told you that your priorities need to be the same as mine.

**You are free to contribute to this project and make whatever improvements you want**; so is anyone else, provided it is beneficial to this app's functionality. I created #107 to concisely describe this problem and allow other volunteers to fix this if they have the time. I value the time spent by volunteers, and don't want them to have to read this entire thread to get to the point.

What more do you want? Should I abandon my life and drop everything to fix this immediate critical flaw in my open source alarm clock that doesn't even affect me? I suppose you expect me to believe that's more important than my grades in college, or my actual paid work that gets me the money to live? Your insistence at pestering me and other contributors is not getting us the slightest bit closer to getting this issue solved.

By the way, I'd like to point out Alarmio's recently-added [Code of Conduct](https://github.com/fennifith/Alarmio/blob/master/CODE_OF_CONDUCT.md). Particularly, the section detailing "unacceptable behavior", which includes insulting comments and harassment. While I greatly value your efforts to help Alarmio achieve a higher form of enlightenment, this conversation is starting to border on those terms. Please take care to ensure that your participation is helpful to the community, and that I don't have to enforce these standards.

If you'd like to do something beneficial for this project, then - as I've said on numerous occasions here - it is open to contributions. However, your comments in this thread have gone past what can be considered helpful. We already understand the problem; I've already read the documentation you have mentioned. Undermining the work that me and all the other contributors to this project have done to get the app to this point, and demanding that we heed your essential commands to immediately fix our obviously broken and improper implementation is helping noone.
