### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by aviallon** [fennifith/Alarmio#142]
Hello,
I know developers (including me) usually dislike this question, but here it is :
Is the project still alive or shall I fork it?
Thanks!

_Sent from my MI 5S Plus using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by Nulide** [comment]
Wondering too, about the current project status.
The last commit in dev-brach is my bug-fix.
That was July.

Maybe he is busy with other stuff.

**Comment by fennifith** [comment]
> Maybe he is busy with other stuff.

Yep.

I was getting a little stressed and had to re-prioritize what I was putting time into. I've since finished classes for this year, so I have a bit of a break before the next semester starts. I still plan on maintaining this project, and will hopefully have another release out soon, though it may take me a while to get back into things.
